application: conky-ddweather-location
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: conky-ddweather-location.application

libraries:
- name: webapp2
  version: latest
- name: webob
  version: latest
